# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Shared folder
  config.vm.synced_folder "..", "/vagrant", type: "virtualbox"

  # vm-jenkins
  config.vm.define "vm-jenkins" do |vm|
    vm.vm.hostname = "vm-jenkins"
    vm.vm.network "private_network", ip: "192.168.56.10"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    vm.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip curl git
    SHELL
  end

  # vm-app (app + monitoring)
  config.vm.define "vm-app" do |vm|
    vm.vm.hostname = "vm-app"
    vm.vm.network "private_network", ip: "192.168.56.11"
    vm.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
    vm.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
      sudo apt-get install -y python3 python3-pip curl git
    SHELL
  end
end
